# fly.toml app configuration file generated for ch-17-newpaper-app-deployment on 2024-01-19T13:30:13+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ch-17-newpaper-app-deployment"
primary_region = "nrt"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
